services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.3
    container_name: household-exit-node-gluetun
    environment:
      - HEALTH_TARGET_ADDRESS=1.1.1.1
    env_file:
      - /opt/docagent/docker/.env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/docagent/docker/household-exit-node/scripts/gluetun-post-rules.txt:/iptables/post-rules.txt:ro
      - wg-config:/gluetun/wireguard:ro
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: household-exit-node-tailscale
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --hostname=${HOST_NAME} --accept-dns=false
      - TS_AUTHKEY=tskey-auth-k8rX26EzDR11CNTRL-3xwcQruge1e5KuGQR7BL2errsqXPqWy8B
    volumes:
      - /opt/docagent/docker/household-exit-node/tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

volumes:
  tailscale-state:
    external: true
    name: tailscale-state
  wg-config:
    external: true
    name: wg-config
